// ─────────────────────────────────────────────
//  Mock orders data — single source of truth
// ─────────────────────────────────────────────

export const STATUS_CONFIG = {
  Delivered:  { variant: "success", label: "Delivered" },
  Shipping:   { variant: "warning", label: "Shipping" },
  Processing: { variant: "info",    label: "Processing" },
  Pending:    { variant: "warning", label: "Pending" },
  Cancelled:  { variant: "danger",  label: "Cancelled" },
  Refunded:   { variant: "danger",  label: "Refunded" },
};

export const ORDERS = [
  {
    id: "4291",
    customer: { name: "Sarah Kim",    email: "sarah.kim@email.com",    phone: "+1 (555) 012-3456", avatar: "SK", avatarBg: "#fef3c7", avatarColor: "#92400e" },
    status: "Delivered",
    date: "2026-03-15",
    deliveredDate: "2026-03-18",
    paymentMethod: "Visa •••• 4291",
    paymentStatus: "Paid",
    shippingAddress: { line1: "14 Maple Street", city: "San Francisco", state: "CA", zip: "94102", country: "US" },
    items: [
      { id: "p1", name: "Air Runner Pro", variant: "Black / Size 42", qty: 1, price: 129.99, emoji: "👟" },
      { id: "p3", name: "Canvas Tote",    variant: "Natural",          qty: 2, price: 34.00,  emoji: "👜" },
    ],
    subtotal: 197.99, shipping: 0,    tax: 15.84, total: 213.83,
    notes: "",
    timeline: [
      { event: "Order placed",      date: "Mar 15, 10:02 AM", done: true  },
      { event: "Payment confirmed", date: "Mar 15, 10:03 AM", done: true  },
      { event: "Picking & packing", date: "Mar 15, 2:40 PM",  done: true  },
      { event: "Shipped",           date: "Mar 16, 9:00 AM",  done: true  },
      { event: "Delivered",         date: "Mar 18, 1:14 PM",  done: true  },
    ],
  },
  {
    id: "4290",
    customer: { name: "James Mensah",  email: "james.mensah@email.com",  phone: "+1 (555) 234-5678", avatar: "JM", avatarBg: "#f0fdf4", avatarColor: "#166534" },
    status: "Shipping",
    date: "2026-03-14",
    deliveredDate: null,
    paymentMethod: "Mastercard •••• 7732",
    paymentStatus: "Paid",
    shippingAddress: { line1: "88 Ocean Ave", city: "Miami", state: "FL", zip: "33101", country: "US" },
    items: [
      { id: "p2", name: "Studio Buds X", variant: "Midnight Black", qty: 1, price: 89.00, emoji: "🎧" },
    ],
    subtotal: 89.00, shipping: 5.99, tax: 7.12, total: 102.11,
    notes: "Please leave at door if no answer.",
    timeline: [
      { event: "Order placed",      date: "Mar 14, 8:15 AM",  done: true  },
      { event: "Payment confirmed", date: "Mar 14, 8:16 AM",  done: true  },
      { event: "Picking & packing", date: "Mar 14, 3:00 PM",  done: true  },
      { event: "Shipped",           date: "Mar 15, 10:00 AM", done: true  },
      { event: "Delivered",         date: "Expected Mar 17",  done: false },
    ],
  },
  {
    id: "4289",
    customer: { name: "Amara Diallo",  email: "amara.diallo@email.com",  phone: "+1 (555) 345-6789", avatar: "AD", avatarBg: "#ede9fe", avatarColor: "#5b21b6" },
    status: "Processing",
    date: "2026-03-14",
    deliveredDate: null,
    paymentMethod: "PayPal",
    paymentStatus: "Paid",
    shippingAddress: { line1: "3 Birch Lane", city: "Austin", state: "TX", zip: "73301", country: "US" },
    items: [
      { id: "p4", name: "Slate Watch", variant: "Graphite",       qty: 1, price: 199.00, emoji: "⌚" },
      { id: "p5", name: "Linen Shirt", variant: "White / Medium", qty: 2, price: 55.00,  emoji: "👔" },
      { id: "p6", name: "Bamboo Lamp", variant: "Natural",        qty: 1, price: 78.00,  emoji: "🪔" },
    ],
    subtotal: 387.00, shipping: 0, tax: 30.96, total: 417.96,
    notes: "",
    timeline: [
      { event: "Order placed",      date: "Mar 14, 6:55 PM",  done: true  },
      { event: "Payment confirmed", date: "Mar 14, 6:56 PM",  done: true  },
      { event: "Picking & packing", date: "In progress",      done: false },
      { event: "Shipped",           date: "Expected Mar 16",  done: false },
      { event: "Delivered",         date: "Expected Mar 19",  done: false },
    ],
  },
  {
    id: "4288",
    customer: { name: "Lena Torres",   email: "lena.torres@email.com",   phone: "+1 (555) 456-7890", avatar: "LT", avatarBg: "#fef2f2", avatarColor: "#991b1b" },
    status: "Cancelled",
    date: "2026-03-13",
    deliveredDate: null,
    paymentMethod: "Visa •••• 8821",
    paymentStatus: "Refunded",
    shippingAddress: { line1: "22 Elm Street", city: "Chicago", state: "IL", zip: "60601", country: "US" },
    items: [
      { id: "p1", name: "Air Runner Pro", variant: "White / Size 38", qty: 1, price: 129.99, emoji: "👟" },
      { id: "p3", name: "Canvas Tote",    variant: "Black",           qty: 1, price: 34.00,  emoji: "👜" },
    ],
    subtotal: 163.99, shipping: 5.99, tax: 13.12, total: 183.10,
    notes: "Customer requested cancellation — wrong size.",
    timeline: [
      { event: "Order placed",      date: "Mar 13, 11:30 AM", done: true },
      { event: "Payment confirmed", date: "Mar 13, 11:31 AM", done: true },
      { event: "Cancelled",         date: "Mar 13, 2:00 PM",  done: true },
      { event: "Refund initiated",  date: "Mar 13, 2:01 PM",  done: true },
      { event: "Refund completed",  date: "Mar 15, 9:00 AM",  done: true },
    ],
  },
  {
    id: "4287",
    customer: { name: "Kwame Asante",  email: "kwame.asante@email.com",  phone: "+1 (555) 567-8901", avatar: "KA", avatarBg: "#f0f9ff", avatarColor: "#075985" },
    status: "Delivered",
    date: "2026-03-12",
    deliveredDate: "2026-03-15",
    paymentMethod: "Mastercard •••• 3310",
    paymentStatus: "Paid",
    shippingAddress: { line1: "77 Cedar Blvd", city: "Seattle", state: "WA", zip: "98101", country: "US" },
    items: [
      { id: "p2", name: "Studio Buds X", variant: "Pearl White", qty: 2, price: 89.00,  emoji: "🎧" },
      { id: "p4", name: "Slate Watch",   variant: "Silver",      qty: 1, price: 199.00, emoji: "⌚" },
      { id: "p6", name: "Bamboo Lamp",   variant: "Dark",        qty: 1, price: 78.00,  emoji: "🪔" },
    ],
    subtotal: 455.00, shipping: 0, tax: 36.40, total: 491.40,
    notes: "",
    timeline: [
      { event: "Order placed",      date: "Mar 12, 9:00 AM",  done: true },
      { event: "Payment confirmed", date: "Mar 12, 9:01 AM",  done: true },
      { event: "Picking & packing", date: "Mar 12, 4:00 PM",  done: true },
      { event: "Shipped",           date: "Mar 13, 8:30 AM",  done: true },
      { event: "Delivered",         date: "Mar 15, 12:45 PM", done: true },
    ],
  },
  {
    id: "4286",
    customer: { name: "Nadia Osei",    email: "nadia.osei@email.com",    phone: "+1 (555) 678-9012", avatar: "NO", avatarBg: "#fdf4ff", avatarColor: "#7e22ce" },
    status: "Shipping",
    date: "2026-03-12",
    deliveredDate: null,
    paymentMethod: "Visa •••• 5544",
    paymentStatus: "Paid",
    shippingAddress: { line1: "5 Pine Road", city: "New York", state: "NY", zip: "10001", country: "US" },
    items: [
      { id: "p5", name: "Linen Shirt", variant: "Beige / Large", qty: 2, price: 55.00, emoji: "👔" },
    ],
    subtotal: 110.00, shipping: 5.99, tax: 8.80, total: 124.79,
    notes: "",
    timeline: [
      { event: "Order placed",      date: "Mar 12, 3:45 PM",  done: true  },
      { event: "Payment confirmed", date: "Mar 12, 3:46 PM",  done: true  },
      { event: "Picking & packing", date: "Mar 13, 10:00 AM", done: true  },
      { event: "Shipped",           date: "Mar 14, 8:00 AM",  done: true  },
      { event: "Delivered",         date: "Expected Mar 17",  done: false },
    ],
  },
  {
    id: "4285",
    customer: { name: "Marcus Reid",   email: "marcus.reid@email.com",   phone: "+1 (555) 789-0123", avatar: "MR", avatarBg: "#fff7ed", avatarColor: "#9a3412" },
    status: "Delivered",
    date: "2026-03-11",
    deliveredDate: "2026-03-14",
    paymentMethod: "Apple Pay",
    paymentStatus: "Paid",
    shippingAddress: { line1: "99 Spruce Way", city: "Denver", state: "CO", zip: "80201", country: "US" },
    items: [
      { id: "p3", name: "Canvas Tote", variant: "Olive", qty: 3, price: 34.00, emoji: "👜" },
    ],
    subtotal: 102.00, shipping: 0, tax: 8.16, total: 110.16,
    notes: "Gift wrap please.",
    timeline: [
      { event: "Order placed",      date: "Mar 11, 1:20 PM",  done: true },
      { event: "Payment confirmed", date: "Mar 11, 1:20 PM",  done: true },
      { event: "Picking & packing", date: "Mar 11, 5:00 PM",  done: true },
      { event: "Shipped",           date: "Mar 12, 7:30 AM",  done: true },
      { event: "Delivered",         date: "Mar 14, 3:00 PM",  done: true },
    ],
  },
  {
    id: "4284",
    customer: { name: "Aisha Conteh",  email: "aisha.conteh@email.com",  phone: "+1 (555) 890-1234", avatar: "AC", avatarBg: "#ecfdf5", avatarColor: "#065f46" },
    status: "Pending",
    date: "2026-03-16",
    deliveredDate: null,
    paymentMethod: "Bank Transfer",
    paymentStatus: "Awaiting payment",
    shippingAddress: { line1: "6 Willow Court", city: "Portland", state: "OR", zip: "97201", country: "US" },
    items: [
      { id: "p1", name: "Air Runner Pro", variant: "Navy / Size 40", qty: 1, price: 129.99, emoji: "👟" },
      { id: "p2", name: "Studio Buds X",  variant: "Rose Gold",      qty: 1, price: 89.00,  emoji: "🎧" },
    ],
    subtotal: 218.99, shipping: 5.99, tax: 17.52, total: 242.50,
    notes: "",
    timeline: [
      { event: "Order placed",      date: "Mar 16, 7:05 AM", done: true  },
      { event: "Payment confirmed", date: "Awaiting",        done: false },
      { event: "Picking & packing", date: "—",               done: false },
      { event: "Shipped",           date: "—",               done: false },
      { event: "Delivered",         date: "—",               done: false },
    ],
  },
];

export const STATUS_COUNTS = {
  All:        ORDERS.length,
  Pending:    ORDERS.filter(o => o.status === "Pending").length,
  Processing: ORDERS.filter(o => o.status === "Processing").length,
  Shipping:   ORDERS.filter(o => o.status === "Shipping").length,
  Delivered:  ORDERS.filter(o => o.status === "Delivered").length,
  Cancelled:  ORDERS.filter(o => o.status === "Cancelled").length,
};
